### ISSUE TITLE
cpu&memery don't have data

### ISSUE THREAD

**Issue by 90show** [scline/docker-cacti#78]
hello,i use the docker cacti&mysql to used.
now cacti can display interface traffice graph,but cpu&memery can't display graph and the debug mode is no data.
 
![微信图片_20201016142302](https://user-images.githubusercontent.com/67131554/96220450-52f4ad80-0fbb-11eb-879d-30f4e33649d2.png)

**Comment by 90show** [comment]
RRDtool Graph Syntax infO:
--
RRDtool Command:/usr/bin/rrdtool graph - \ --imgformat=PNG \ --start='1602742800' \ --end='1602828922' \ --pango-markup  \ --title='test-240-1 - CPU Usage' \ --vertical-label='percent' \ --slope-mode \ --base=1000 \ --height=120 \ --width=500 \ --tabwidth '30' \ --rigid \ --alt-autoscale-max \ --lower-limit='0' \ COMMENT:"From 2020/10/15 14\:20\:00 To 2020/10/16 14\:15\:22\c" \ COMMENT:"  \n" \ --border 1 --slope-mode \ --watermark 'Generated by Cacti' \ DEF:a='/cacti/rra/729/35306.rrd':'5min_cpu':AVERAGE \ AREA:a#ED5394FF:'CPU Usage'  \ GPRINT:a:LAST:'Current\:%8.0lf'  \ GPRINT:a:AVERAGE:'Average\:%8.0lf'  \ GPRINT:a:MAX:'Maximum\:%8.0lf' RRDtool Command lengths = 609 charaters.RRDtool Says:OK

**Comment by 90show** [comment]
RRDtool info:
RRDtool Command:
/usr/bin/rrdtool graph - \
--imgformat=PNG \
--start='1602742800' \
--end='1602828922' \
--pango-markup  \
--title='test-240-1 - CPU Usage' \
--vertical-label='percent' \
--slope-mode \
--base=1000 \
--height=120 \
--width=500 \
--tabwidth '30' \
--rigid \
--alt-autoscale-max \
--lower-limit='0' \
COMMENT:"From 2020/10/15 14\:20\:00 To 2020/10/16 14\:15\:22\c" \
COMMENT:"  \n" \
--border 1 --slope-mode \
--watermark 'Generated by Cacti' \
DEF:a='/cacti/rra/729/35306.rrd':'5min_cpu':AVERAGE \
AREA:a#ED5394FF:'CPU Usage'  \
GPRINT:a:LAST:'Current\:%8.0lf'  \
GPRINT:a:AVERAGE:'Average\:%8.0lf'  \
GPRINT:a:MAX:'Maximum\:%8.0lf' 
RRDtool Command lengths = 609 charaters.
RRDtool Says:
OK

**Comment by scline** [comment]
This could be caused by a number of things, the device your hitting not be accessible or SNMP queries being wrong for example. This issue however isn't related to the dockerization of cacti and more functional usage Cacti as a whole. 

I recommend posting this question to the Cacti help and support forums where they would be able to troubleshoot this issue with you. I would add information about what device your hitting and SNMP/Datastores you're using including the information you already presented. Cacti debug logging can also help pinpoint the issue.

https://forums.cacti.net/

**Comment by 90show** [comment]
thanks
